# Generated by Django 6.0.3 on 2026-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_category_options_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(default='', help_text="Mahsulotlar ro'yxati", verbose_name='Buyurtma tarkibi'),
        ),
    ]
